# Nombre del Workflow
name: Uso de variables y secretos
# Inicio del workflow
on:
  # Se ejecuta cuando hacemos git push
  push:
    # Solo se ejecutara si el push fue realizado sobre la rama main
    branches: [ "main" ]
# Jobs que ejecutara el workflow
jobs:
  # Nombre o identificador del job (ejm: build o deploy nombre libre)
  print-secrets-token:
    # GitHub crea una maquina virtual conla ultima version de Ubuntu donde se ejecutara el workflow
    runs-on: ubuntu-latest
    # Pasos del job
    steps:
      # Nombre descriptivo del paso
      - name: Mostrar variable de entorno
        # Se declaran Variables de entorno 
        env:
          # Crea una variable llamada MI_VARIABLE con el valor ValorDeEjemplo
          MI_VARIABLE: "ValorDeEjemplo"
        # Èjecucion de comandos en la terminal. EL simpbolo | indica que pueden escribirse varias lineas de comandos.
        run: |    # Todo lo que viene debajo sera ejecutado en la terminal.
          echo "Variable de entorno: ${{ env.MI_VARIABLE }}" 
      # Segundo paso
      - name: Visualizacion de Secretos
        # Los comandos se ejecutaran usando Bash. Ubuntu lo hace habitualmente, pero aqui lo especifica de forma explicita.
        shell: bash
        # Declaracion de variables para este paso
        env:
          # Crea la variable de entorno SUPER_SECRET con el valor de MI_SECRETO que previamente se creo en 
          # Settings->Secrets and Variables->Actions
          SUPER_SECRET: ${{ secrets.MI_SECRETO }}
        run: |  # Uso del secreto. En Bash las variables se utilizan con $SUPER_SECRET , la cual estara enmascarada por seguridad
          echo "Tu mayor secreto es: $SUPER_SECRET, vaya no puede conocerse..."
      # Tercer Paso
      - name: Visualizacion de variables y comandos
        shell: bash # Los comandos se ejucutaran usando bash
        env: # Declaracion de variables de entorno 
          SUPER_SECRET: ${{ secrets.MI_SECRETO }} # Variable de entorno
        run: |
          echo "Primeras 3 letras del secreto: "$(cut -c 1-3 <<< $SUPER_SECRET)", es correcto?"


